#pragma config(Sensor, S1,     snsrforce,      sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
// Simple program to test HiTechnic Force Sensor.
//
// Hitechnic force sensor is configured as an ambient light sensor.
task main()
{
  int val = 0;
int raw = 0;
eraseDisplay();
// loop and poll the sensor.
while (true)
{
    val = SensorValue[snsrforce];
raw = SensorRaw[snsrforce];
nxtDisplayCenteredTextLine(0, "Force Test");
// display normalized value.
nxtDisplayCenteredTextLine(1, "val:%4d", val);
// display the raw output value.
nxtDisplayCenteredTextLine(2, "raw:%4d", raw);
wait10Msec(10);
  }
}
