#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S4,     IRseeker2,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servo2,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)    // Infinite loop:
	{
  	nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[IRseeker2]);    // Display "Sensor Value: ##"
  	wait1Msec(100);    // Wait 100 milliseconds to help display correctly.
	}
}
