#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     IRseeker2,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     armMotor,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     scoopMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     specMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    lockingServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
  // Place code here to initialize servos to starting positions.

  if (nAvgBatteryLevel < 8000) {  // brick under 8.0 volts
	  PlayImmediateTone(1000, 100);  // play a warning tone
    PlaySoundFile("NxtBatteryLow.rso");
  }

  if (externalBatteryAvg < 12000) {  // main battery under 12.0
    int i;
    // play a warning siren once for
    // every tenth of a volt too low
    for (i = 0; i < (14000 - externalBatteryAvg) / 100; i++) {
      PlayImmediateTone(2000, 300);  // play a warning tone
      PlaySoundFile("ExternalBatteryLow.rso");
    }
  }

  return;
}

task main()
{
	initializeRobot();
	bool BeaconFound = false;
	int waittime = 550;

	//waitForStart();
	motor[rightMotor] = -100;
	motor[leftMotor] = -100;
	wait1Msec(1000);
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;

	motor[leftMotor] = 0;
	motor[rightMotor] = -100;
	wait1Msec(1100);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	ClearTimer(T1);
	while(time1[T1] <= 4000){

	motor[leftMotor] = -100;
	motor[rightMotor] = -100;

	if(SensorValue[IRseeker2] == 5)
	{
		ClearTimer(T2);
		wait1Msec(waittime);

		motor[leftMotor] = 0;
		motor[rightMotor] = 0;

		motor[specMotor] = -20;
		wait1Msec(1000);
		motor[specMotor] = 0;
		wait1Msec(100);
		motor[specMotor] = 20;
		wait1Msec(1000);
		motor[specMotor] = 0;
		BeaconFound = true;

		if(time1[T2] < 2400)
		{
			motor[rightMotor] = -100;
			motor[leftMotor] = -100;
			wait1Msec(1000);
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;
		}else{
			wait1Msec(5000000000000000000000000000000);
		}

		if(time1[T2] > 2400 && BeaconFound == false)
		{
			waittime = .750;
		}
	}
}
}
