#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor4,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	initializeRobot();   // Initialize The Robot's Servos and Motor's

  waitForStart();   // wait for start of tele-op phase

  while(true)
  {
  	if(joy1Btn(3) == 1)
  	{
  		motor[motor1] = 50
  		motor[motor2
  	}
  }




}
